/**
 * 
 */
package com.bankMitra.repository.bankenduserpanel;

import java.util.List;

import javax.validation.Valid;

import com.bankMitra.exception.DataAccessException;
import com.bankMitra.model.admin.LoanSchemeRequest;
import com.bankMitra.model.admin.response.LoanSchemeResponse;
import com.bankMitra.model.admin.response.LoanVariantResponse;
import com.bankMitra.model.bankenduserpanel.request.AdministrativeRequest;
import com.bankMitra.model.bankenduserpanel.request.ComercialCreditFacilityRequest;
import com.bankMitra.model.bankenduserpanel.request.DueDeligenceAuditProcessRequest;
import com.bankMitra.model.bankenduserpanel.request.DueDeligenceCoApplicantRequest;
import com.bankMitra.model.bankenduserpanel.request.DueDeligenceGeneralInfoRequest;
import com.bankMitra.model.bankenduserpanel.request.DueDeligenceProcessRequest;
import com.bankMitra.model.bankenduserpanel.request.NewDueDeligenceProcessRequest;
import com.bankMitra.model.bankenduserpanel.request.ViewDueDeligenceRequest;
import com.bankMitra.model.bankenduserpanel.response.AccountType;
import com.bankMitra.model.bankenduserpanel.response.AdministrativeResponse;
import com.bankMitra.model.bankenduserpanel.response.AutoGeneratedResponse;
import com.bankMitra.model.bankenduserpanel.response.BorrowerCategory;
import com.bankMitra.model.bankenduserpanel.response.BranchCheckerResponse;
import com.bankMitra.model.bankenduserpanel.response.BranchMakerResponse;
import com.bankMitra.model.bankenduserpanel.response.BranchNameResponse;
import com.bankMitra.model.bankenduserpanel.response.BranchSAResponse;
import com.bankMitra.model.bankenduserpanel.response.Checkers;
import com.bankMitra.model.bankenduserpanel.response.CifRegistrationResponse;
import com.bankMitra.model.bankenduserpanel.response.CoApplicant;
import com.bankMitra.model.bankenduserpanel.response.ComercialCreditFacilityDetails;
import com.bankMitra.model.bankenduserpanel.response.DueDeligenceAuditProcessResponse;
import com.bankMitra.model.bankenduserpanel.response.DueDeligenceCoApplicantGurantorResponse;
import com.bankMitra.model.bankenduserpanel.response.DueDeligenceCoApplicantResponse;
import com.bankMitra.model.bankenduserpanel.response.DueDeligenceGeneralInfoResponse;
import com.bankMitra.model.bankenduserpanel.response.DueDeligenceProcessResponse;
import com.bankMitra.model.bankenduserpanel.response.LoanSAResponse;
import com.bankMitra.model.bankenduserpanel.response.Makers;
import com.bankMitra.model.bankenduserpanel.response.NewDueDeligencePageResponse;
import com.bankMitra.model.bankenduserpanel.response.NewDueDeligenceProcessResponse;
import com.bankMitra.model.bankenduserpanel.response.ReportData;
import com.bankMitra.model.bankenduserpanel.response.ReportHeaderResponse;
import com.bankMitra.model.bankenduserpanel.response.ReportingActionResponse;
import com.bankMitra.model.bankenduserpanel.response.ReportingTableData;
import com.bankMitra.model.bankenduserpanel.response.SaveViewDDM2M5Request;
import com.bankMitra.model.bankenduserpanel.response.SaveViewDDRequest;
import com.bankMitra.model.bankenduserpanel.response.SaveViewDDResponse;
import com.bankMitra.model.bankenduserpanel.response.UnitChecker;
import com.bankMitra.model.bankenduserpanel.response.ViewDueDeligenceResponse;
import com.bankMitra.model.clientManagement.response.MovableProperty;
import com.bankMitra.model.reference.BorrowerType;
import com.bankMitra.model.reference.LoanVariant;
import com.bankMitra.model.reference.RiskType;

/**
 * @author Bank Maitra
 *
 */
public interface InitiateDueDeligenceRepository {

	DueDeligenceProcessResponse processDueDeligence(@Valid DueDeligenceProcessRequest dueDeligenceProcessRequest) throws DataAccessException;

	DueDeligenceAuditProcessResponse processAuditDueDeligence(
			DueDeligenceAuditProcessRequest dueDeligenceProcessRequest) throws DataAccessException;

	NewDueDeligenceProcessResponse initiateNewDueDeligence(NewDueDeligenceProcessRequest dueDeligenceProcessRequest) throws DataAccessException;

	List<CoApplicant> getListOfCoapplicantDesignation() throws DataAccessException;

	List<LoanVariantResponse> getListOfLoanSchemeForFacilities(@Valid LoanSchemeRequest loanSchemeFacilitiesRequest) throws DataAccessException;

	List<BorrowerType> getListOfBorrowerTypes() throws DataAccessException;

	List<AccountType> getListOfAccountTypes() throws DataAccessException;

	List<LoanVariantResponse> getListOfloanVariants(@Valid LoanVariant loanVariantRequest) throws DataAccessException;

	List<LoanSchemeResponse> getListOfLoanSchemes(@Valid LoanSchemeRequest loanSchemeRequest) throws DataAccessException;

	List<Makers> getListOfAuditFirmMaker(Integer clientId) throws DataAccessException;

	List<Checkers> getListOfAuditFirmChecker(Integer clientId) throws DataAccessException;

	List<BranchNameResponse> getListOfBranchNames(Integer clientId) throws DataAccessException;

	List<ComercialCreditFacilityDetails> getCommercialCreditFacilities(
			ComercialCreditFacilityRequest comercialCreditFacilityRequest) throws DataAccessException;

	List<CifRegistrationResponse> getListOfCIF(String clientId) throws DataAccessException;

	List<BranchMakerResponse> getBranchMaker(Integer clientGroupId)  throws DataAccessException;

	List<BranchCheckerResponse> getBranchChecker(Integer clientGroupId) throws DataAccessException;

	List<BranchSAResponse> getBranchSA(Integer clientGroupId) throws DataAccessException;

	List<LoanSAResponse> getLoanSA(Integer clientGroupId) throws DataAccessException;

	List<BorrowerCategory> getListOfBorrowerCategory()  throws DataAccessException;

	List<MovableProperty> getListOfMovableProperties() throws DataAccessException;

	List<DueDeligenceProcessResponse> getNewDueDiligencePageDetails(DueDeligenceProcessRequest dueDeligenceRequest)
			throws DataAccessException;

	AutoGeneratedResponse getAutoGeneratedDetails(String loanAppId) throws DataAccessException;

	AdministrativeResponse saveAdministrativeDetails(AdministrativeRequest adminRequest)  throws DataAccessException;

	List<UnitChecker> getListOfUnitChecker(String clientGroupId) throws DataAccessException;

	UnitChecker getDefaultUnitChecker(String e2eNum)  throws DataAccessException;

	DueDeligenceGeneralInfoResponse saveDueDiligenceGeneralInfo(DueDeligenceGeneralInfoRequest dueDeligenceRequest) throws DataAccessException;

	DueDeligenceGeneralInfoResponse getDueDiligenceGeneralInfo(String e2eNum) throws DataAccessException;

	DueDeligenceCoApplicantResponse saveDueDiligenceCoApplicant(DueDeligenceCoApplicantRequest dueDeligenceRequest) throws DataAccessException;

	DueDeligenceCoApplicantRequest getDueDiligenceCoApplicantDetails(String e2eNum) throws DataAccessException;

	DueDeligenceCoApplicantResponse getDueDiligenceCollateralSecurity(String e2eNum) throws DataAccessException;

	List<DueDeligenceCoApplicantGurantorResponse> getDueDiligenceGurantor(String e2eNum) throws DataAccessException;

	List<MovableProperty> getDueDiligenceMoveableProperty(String e2eNum)  throws DataAccessException;

	List<ViewDueDeligenceResponse> viewDueDiligence(ViewDueDeligenceRequest dueDeligenceRequest) throws DataAccessException;

	List<ViewDueDeligenceResponse> viewDetailsForDueDiligence(ViewDueDeligenceRequest dueDeligenceRequest) throws DataAccessException;

	List<ReportHeaderResponse> getReportingHeader(String e2eNum);
	
	List<ReportingActionResponse> getReportingAction(String userName);
	
	Boolean isComplianceReportUpdated(String e2eNum) throws DataAccessException;
	
	List<ReportingTableData> getReportTableData(String e2eNum);
	
	String getReportUpdateStatus(String userName, String e2eNum, Integer actionId) throws DataAccessException;
	
	String getDynamicQueryForGenerateReport (String e2eNum, String rowName, String columnName) throws DataAccessException;
	
	List<ReportData> getReportData(String query);
	
	SaveViewDDResponse saveViewDDDB (SaveViewDDRequest request) throws DataAccessException;
	
	SaveViewDDResponse saveViewDD_M2_M5_DB (SaveViewDDM2M5Request request) throws DataAccessException;
	
	List<RiskType> getRiskTypeId(Integer clientId) throws DataAccessException;
}
