/**
 * 
 */
package com.bankMitra.repository.bankenduserpanel.rowmapper;

/**
 * @author BankMitra
 *
 */
import org.springframework.jdbc.core.RowMapper;

import com.bankMitra.model.bankenduserpanel.response.AutoGeneratedResponse;

import java.sql.ResultSet;
import java.sql.SQLException;

public class AutoGeneratedRowMapper implements RowMapper<AutoGeneratedResponse> {

    public AutoGeneratedResponse mapRow(ResultSet rs, int rowNum) throws SQLException {

    	AutoGeneratedResponse resp = new AutoGeneratedResponse();
    	resp.setE2eno(rs.getString("e2e_no"));
    	resp.setE2edate(String.valueOf(rs.getDate("e2e_date")));
    	resp.setE2em3expectedstartdate(String.valueOf(rs.getDate("e2e_m3_expected_start_date")));
    	resp.setE2em4expectedstartdate(String.valueOf(rs.getDate("e2e_m4_expected_start_date")));
    	resp.setE2em4reviewdate(String.valueOf(rs.getDate("e2e_m4_review_date")));
    	resp.setE2em4reviewno(String.valueOf(rs.getInt("e2e_m4_review_no")));
    	resp.setE2em5securityreleasenumber(String.valueOf(rs.getInt("e2e_m5_security_release_number")));
    	resp.setE2em5date(String.valueOf(rs.getDate("e2e_m5_date")));
    	resp.setIfsccode(rs.getString("ifsc_code"));
        return resp;

    }
}
