/**
 * 
 */
package com.bankMitra.model.bankenduserpanel.response;

import java.io.Serializable;
import java.util.Date;

/**
 * @author BankMitra
 *
 */
public class AutoGeneratedResponse implements Serializable{
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -8558651600485195374L;

	private String e2eno;
	private String e2edate;
	private String e2em3expectedstartdate;
	private String e2em4expectedstartdate;
	private String e2em4reviewdate;
	private String e2em4reviewno;
	private String e2em5securityreleasenumber;
	private String e2em5date;
	private String ifsccode;
	
	private String messageCode;
	
	private String messageDescription;
	/**
	 * @return the e2eno
	 */
	public String getE2eno() {
		return e2eno;
	}
	/**
	 * @param e2eno the e2eno to set
	 */
	public void setE2eno(String e2eno) {
		this.e2eno = e2eno;
	}
	/**
	 * @return the e2edate
	 */
	public String getE2edate() {
		return e2edate;
	}
	/**
	 * @param e2edate the e2edate to set
	 */
	public void setE2edate(String e2edate) {
		this.e2edate = e2edate;
	}
	/**
	 * @return the e2em3expectedstartdate
	 */
	public String getE2em3expectedstartdate() {
		return e2em3expectedstartdate;
	}
	/**
	 * @param e2em3expectedstartdate the e2em3expectedstartdate to set
	 */
	public void setE2em3expectedstartdate(String e2em3expectedstartdate) {
		this.e2em3expectedstartdate = e2em3expectedstartdate;
	}
	/**
	 * @return the e2em4expectedstartdate
	 */
	public String getE2em4expectedstartdate() {
		return e2em4expectedstartdate;
	}
	/**
	 * @param e2em4expectedstartdate the e2em4expectedstartdate to set
	 */
	public void setE2em4expectedstartdate(String e2em4expectedstartdate) {
		this.e2em4expectedstartdate = e2em4expectedstartdate;
	}
	/**
	 * @return the e2em4reviewdate
	 */
	public String getE2em4reviewdate() {
		return e2em4reviewdate;
	}
	/**
	 * @param e2em4reviewdate the e2em4reviewdate to set
	 */
	public void setE2em4reviewdate(String e2em4reviewdate) {
		this.e2em4reviewdate = e2em4reviewdate;
	}
	/**
	 * @return the e2em4reviewno
	 */
	public String getE2em4reviewno() {
		return e2em4reviewno;
	}
	/**
	 * @param e2em4reviewno the e2em4reviewno to set
	 */
	public void setE2em4reviewno(String e2em4reviewno) {
		this.e2em4reviewno = e2em4reviewno;
	}
	/**
	 * @return the e2em5securityreleasenumber
	 */
	public String getE2em5securityreleasenumber() {
		return e2em5securityreleasenumber;
	}
	/**
	 * @param e2em5securityreleasenumber the e2em5securityreleasenumber to set
	 */
	public void setE2em5securityreleasenumber(String e2em5securityreleasenumber) {
		this.e2em5securityreleasenumber = e2em5securityreleasenumber;
	}
	/**
	 * @return the e2em5date
	 */
	public String getE2em5date() {
		return e2em5date;
	}
	/**
	 * @param e2em5date the e2em5date to set
	 */
	public void setE2em5date(String e2em5date) {
		this.e2em5date = e2em5date;
	}
	/**
	 * @return the ifsccode
	 */
	public String getIfsccode() {
		return ifsccode;
	}
	/**
	 * @param ifsccode the ifsccode to set
	 */
	public void setIfsccode(String ifsccode) {
		this.ifsccode = ifsccode;
	}
	/**
	 * @return the messageCode
	 */
	public String getMessageCode() {
		return messageCode;
	}
	/**
	 * @param messageCode the messageCode to set
	 */
	public void setMessageCode(String messageCode) {
		this.messageCode = messageCode;
	}
	/**
	 * @return the messageDescription
	 */
	public String getMessageDescription() {
		return messageDescription;
	}
	/**
	 * @param messageDescription the messageDescription to set
	 */
	public void setMessageDescription(String messageDescription) {
		this.messageDescription = messageDescription;
	}
	
}
